src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    const STATUT_LIBELLES = [
        0 => 'Invalide',
        1 => 'En cours',
        2 => 'Terminé',
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_utilisateur;

    /**
     * @ORM\Column(type="date")
     */
    private $date_commande;

    /**
     * @ORM\Column(type="integer")
     */
    private $statut;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneCommande", mappedBy="id_commande")
     */
    private $ligneCommandes;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUtilisateur(): ?Utilisateur
    {
        return $this->id_utilisateur;
    }

    public function setIdUtilisateur(?Utilisateur $id_utilisateur): self
    {
        $this->id_utilisateur = $id_utilisateur;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getStatut(): ?int
    {
        return $this->statut;
    }

    public function getStatutLibelle(): string
    {
        if ($this->statut) {
            return self::STATUT_LIBELLES[$this->statut];
        } else {
            return self::STATUT_LIBELLES[0];
        }
    }

    public function setStatut(int $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getLigneCommandes()
    {
        return $this->ligneCommandes;
    }

    public function setLigneCommandes($ligneCommandes): self
    {
        $this->ligneCommandes = $ligneCommandes;

        return $this;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setIdCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes->removeElement($ligneCommande);
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getIdCommande() === $this) {
                $ligneCommande->setIdCommande(null);
            }
        }

        return $this;
    }
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UtilisateurRepository")
 */
class Utilisateur implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="id_utilisateur")
     */
    private $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return bool
     */
    public function isAdmin(): bool
    {
        return (in_array('ROLE_ADMIN', $this->roles));
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setIdUtilisateur($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getIdUtilisateur() === $this) {
                $commande->setIdUtilisateur(null);
            }
        }

        return $this;
    }
}

src/Form/UtilisateurType.php
<?php

namespace App\Form;

use App\Entity\Utilisateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UtilisateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class, ['label' => false, 'attr' => ['placeholder' => 'Adresse e-mail']])
            ->add('password', PasswordType::class, ['label' => false, 'attr' => ['placeholder' => 'Mot de passe']])
            ->add('nom', TextType::class, ['label' => false, 'attr' => ['placeholder' => 'Nom']])
            ->add('prenom', TextType::class, ['label' => false, 'attr' => ['placeholder' => 'Prénom']]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Utilisateur::class,
        ]);
    }
}

src/Controller/UtilisateurController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Entity\LigneCommande;
use App\Entity\Utilisateur;
use App\Form\UtilisateurType;
use App\Repository\UtilisateurRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use Doctrine\ORM\TransactionRequiredException;
use phpDocumentor\Reflection\Types\Collection;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/utilisateur")
 */
class UtilisateurController extends AbstractController
{
    /**
     * @Route("/index", name="utilisateur_index")
     * @param UtilisateurRepository $utilisateurRepository
     * @return Response
     */
    public function index(UtilisateurRepository $utilisateurRepository): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }

        $commandes = $this->getDoctrine()->getRepository(Commande::class)->findBy(['id_utilisateur' => $this->getUser()->getId()]);

        foreach ($commandes as $commande) {
            $ligneCommandes = $this->getDoctrine()->getRepository(LigneCommande::class)->findBy(['id_commande' => $commande->getId()]);
            $commande->setLigneCommandes($ligneCommandes);
        }


        return $this->render('utilisateur/index.html.twig', [
            'utilisateur' => $this->getUser(),
            'commandes' => $commandes,
        ]);
    }

    /**
     * @Route("/show", name="show_users")
     */
    public function show()
    {
        if ($this->getUser() && $this->getUser()->isAdmin()) {
            $utilisateurs = $this->getDoctrine()->getRepository(Utilisateur::class)->findAll();

            return $this->render('utilisateur/show.html.twig', [
                'utilisateurs' => $utilisateurs,
            ]);
        }

        return $this->redirectToRoute('index');
    }

    /*
     * Création automatique d'un utilisateur
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $utilisateur = new Utilisateur();
        $form = $this->createForm(UtilisateurType::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Encryptage du mdp et définition du rôle CLIENT
            $utilisateur->setPassword($passwordEncoder->encodePassword($utilisateur, $utilisateur->getPassword()));
            $utilisateur->setRoles(['ROLE_CLIENT']);

            // Sauvegarde
            try {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($utilisateur);
                $entityManager->flush();
            } catch (\Exception $exception) {
                $this->addFlash('error', 'L\'e-mail existe déjà');
                return $this->redirectToRoute('utilisateur_inscription');
            }

            $this->get('session')->set('user', $utilisateur);

            return $this->redirectToRoute('app_login');
        }

        return $this->render('utilisateur/new.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{utilisateur}", name="utilisateur_delete")
     * @param Utilisateur $utilisateur
     * @return RedirectResponse
     */
    public function delete(Utilisateur $utilisateur)
    {
        // Action d'un admin
        if ($this->getUser() && $this->getUser()->isAdmin()) {

            if ($utilisateur) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->remove($utilisateur);
                $entityManager->flush();
            }

            return $this->redirectToRoute('show_users');
        }

        return $this->redirectToRoute('index');
    }

    /**
     * @Route("/updaterank/{utilisateur}", name="utilisateur_updaterank")
     * @param Utilisateur $utilisateur
     * @return RedirectResponse
     */
    public function updateRank(Utilisateur $utilisateur)
    {
        // Action d'un admin
        if ($this->getUser() && $this->getUser()->isAdmin()) {

            if ($utilisateur) {
                $role = ($utilisateur->isAdmin()) ? 'ROLE_USER' : 'ROLE_ADMIN';
                $utilisateur->setRoles([$role]);
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($utilisateur);
                $entityManager->flush();
            }

            return $this->redirectToRoute('show_users');
        }

        return $this->redirectToRoute('index');
    }
}

templates/utilisateur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('S\'inscrire') }}</button>
{{ form_end(form) }}

templates/utilisateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Espace Membre{% endblock %}

{% block body %}
    <section>
        <div class="container">
            <h1>Vos commandes</h1>
            {% for commande in commandes %}

                <div class="card mb-2">
                    <div class="card-body">
                        <h5 class="card-title">Commande #{{ commande.id }} - {{ commande.statutLibelle }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Passée le {{ commande.dateCommande|date('d/m/y') }}</h6>
                        <p class="card-text">
                            {% for ligneCommande in commande.ligneCommandes %}
                                {{ ligneCommande.quantite }}x {{ ligneCommande.getIdArticle().libelle }} - {{ ligneCommande.prix }} €<br/>
                            {% endfor %}
                        </p>
                    </div>
                </div>

            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/utilisateur/new.html.twig
{% extends 'base.html.twig' %}


{% block title %}Inscription{% endblock %}
{% block body %}
    <section class="ftco-section">
        <div class="container">
            <h1>Inscription</h1>
            {% for label, messages in app.flashes(['warning', 'error']) %}
                {% for message in messages %}
                    <div class="alert alert-{{ label }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endfor %}
            {{ include('utilisateur/_form.html.twig') }}
        </div>
    </section>
{% endblock %}

templates/utilisateur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion utilisateurs{% endblock %}

{% block body %}
    <section>
        <div class="container">
                <h1>Gestion des utilisateurs</h1>

                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Email</th>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Est admin</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for utilisateur in utilisateurs %}
                        <tr>
                            <td>{{ utilisateur.id }}</td>
                            <td>{{ utilisateur.email }}</td>
                            <td>{{ utilisateur.nom }}</td>
                            <td>{{ utilisateur.prenom }}</td>
                            <td>
                                <a href="{{ path('utilisateur_updaterank', {'utilisateur': utilisateur.id}) }}" class="badge p-2 badge-{% if 'ROLE_ADMIN' in utilisateur.roles %}info{% else %}warning{% endif %}">{% if 'ROLE_ADMIN' in utilisateur.roles %}OUI{% else %}NON{% endif %}</a>
                                <a href="{{ path('utilisateur_delete', {'utilisateur': utilisateur.id}) }}" class="badge p-2 badge-danger">Supprimer</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
        </div>
    </section>
{% endblock %}